region: eu-west-1
environment_tag: "Development"
s3BucketName_webapp_code: codepipeline-vue-pwa-crypto-checker-webapp-hosting-dev
s3BucketPolicy_cloudfront_origin_access_identity: { "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E1RUIKOKBYLHTO" }
